services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qtd_tsoftware           # Tên database
      MYSQL_USER: myuser                      # Tên người dùng
      MYSQL_PASSWORD: mypassword              # Mật khẩu người dùng
      MYSQL_ROOT_PASSWORD: myrootpassword     # Mật khẩu root
    networks:
      - keycloak_network
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin                   # Tài khoản quản trị Keycloak
      KEYCLOAK_ADMIN_PASSWORD: admin          # Mật khẩu tài khoản quản trị
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql/qtd_tsoftware       # Đường dẫn kết nối MySQL
      KC_DB_USERNAME: myuser                  # Người dùng khớp với MySQL
      KC_DB_PASSWORD: mypassword              # Mật khẩu khớp với MySQL
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true # Bật phục hồi giao dịch
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/keycloak.json # Đường dẫn import cụ thể
    ports:
      - 8180:8080
    restart: always
    volumes:
      - ./keycloak:/opt/keycloak/data/import  # Thư mục chứa file import Keycloak
    depends_on:
      - mysql
    networks:
      - keycloak_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql                         # MySQL host
      PMA_PORT: 3306                          # MySQL port
      PMA_ARBITRARY: 1                        # Cho phép kết nối với server tùy ý
    ports:
      - 8181:80                               # Mở cổng phpMyAdmin trên 8180
    networks:
      - keycloak_network

volumes:
  mysql_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
