services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: qtd_tsoftware
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - keycloak_network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/qtd_tsoftware
      KC_DB_USERNAME: myuser
      KC_DB_PASSWORD: mypassword
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/tsoftware-realm.json
    ports:
      - 8180:8080
    restart: always
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - keycloak_network


volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
