server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: qtd-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_URI}

idp:
  url: ${IDP_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  realm: tsoftware

springdoc: ### https://springdoc.org/#springdoc-applications-demos
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
