server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: false

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: qtd-service
  datasource:
    url: jdbc:postgresql://localhost:5432/qtd_tsoftware
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    require-ssl: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tsoftware

idp:
  server-url: http://localhost:8180
  client-id: server
  client-secret: InJyrLbMC4DZezpzAUbFDdtTXykeFXff
  realm: tsoftware

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    oauth:
      client-id: web


google:
  cloud:
    storage:
      bucket-name: qtd_tsoftware
      service-account: service-account.json

t-software:
  workflow:
    rules:
      register:
        cancel: true
        login: isSuccess == true
        denied: isSuccess == false
      create_customer:
        submit_loan_request: true
      submit_loan_request:
        submit_loan_plan: true
      submit_loan_plan:
        review: approved == true



