server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    bundle: qtd-server
    client-auth: want

spring:
  ssl:
    bundle:
      jks:
        qtd-server:
          key:
            alias: ${KEY_ALIAS}
            password: ${STORE_PASSWORD}
          keystore:
            location: classpath:server.p12
            password: ${STORE_PASSWORD}
            type: PKCS12
#          truststore:
#            location: classpath:server.p12
#            password:  ${STORE_PASSWORD}
#            type: PKCS12
  threads:
    virtual:
      enabled: true
  application:
    name: qtd-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_URI}



idp:
  server-url: ${IDP_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  realm: ${IDP_REALM}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    oauth:
      client-id: web


google:
  cloud:
    storage:
      bucket-name: qtd_tsoftware
      service-account: service-account.json