server:
  port: 8080
  servlet:
    context-path: /profile
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: qtd-service
  datasource:
    url: jdbc:postgresql://localhost:5432/qtd_tsoftware
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tsoftware

idp:
  url: http://localhost:8180
  client-id: tsoftware_backend
  client-secret: jqUtYH7iycezKv1hq02MjznaBCRcIiSB
  realm: tsoftware
