server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    bundle: web-server
    client-auth: want


spring:
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${KEY_ALIAS}
            password: ${STORE_PASSWORD}
          keystore:
            location: classpath:server.p12
            password: ${STORE_PASSWORD}
            type: PKCS12

  threads:
    virtual:
      enabled: true
  application:
    name: qtd-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_URI}

  mail:
    host: ${HOST_MAIL}
    port: ${PORT_MAIL}
    username: ${USER_MAIL}
    password: ${PAW_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

idp:
  server-url: ${IDP_URL}
  server-external-url: ${IDP_EXTERNAL_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  realm: ${IDP_REALM}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    oauth:
      client-id: web

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%clr(%X{TraceId}){yellow}] %m%n%wex"

google:
  cloud:
    storage:
      bucket-name: qtd_tsoftware
      service-account: service-account.json

workflow:
  rules:
    onboarding:
      - step: init
        dependencies: []
        nextStepRules:
          - step: loan-request
            condition: "true"
          - step: loan-plan
            condition: "true"
          - step: create-financial-info
            condition: "true"

      - step: create-loan-request
        extractStatus: "@speLConfig.extractStatus(#step)"
        type: action
        dependencies:
          - init
        nextStepRules:
          - step: add-asset-collateral
            condition: "#root.steps.?[#this.name == 'create-loan-request'][0].histories[-1].response.workflowTransactionResponse.metadata.amount > 50000000"
          - step: create-credit-rating
            condition: "true"

      - step: create-loan-plan
        type: action
        extractStatus: "@speLConfig.extractStatus(#step)"
        dependencies:
          - init
        nextStepRules:
          - step: create-credit-rating
            condition: "true"

      - step: create-financial-info
        type: action
        extractStatus: "@speLConfig.extractStatus(#step)"
        dependencies:
          - init
        nextStepRules:
          - step: create-credit-rating
            condition: "true"

      - step: add-asset-collateral
        dependencies:
          - financial-info
          - create-loan-plan
          - create-loan-request
        nextStepRules:
          - step: create-valuation-meting
            condition: "true"

      - step: create-valuation-meting
        dependencies:
          -  add-asset-collateral
        nextStepRules:
          - step: create-valuation-report
            condition: "true"

      - step: create-valuation-report
        type: action
        extractStatus: "@speLConfig.extractStatus(#step)"
        dependencies:
          - create-valuation-meting
        nextStepRules:
          - step: create-appraisal-meting
            condition: "true"

      - step: create-credit-rating
        dependencies:
          - financial-info
          - create-loan-plan
          - create-loan-request
        nextStepRules:
          - step: create-appraisal-meting
            condition: "true"

      - step:  create-appraisal-meting
        dependencies:
          - create-credit-rating
          - create-valuation-report
        nextStepRules:
          - step: create-appraisal-report
            condition: "true"
