services:
  postgres:
    container_name: qtd-postgres
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_INITDB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - qtd_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: qtd-keycloak
    command: start  --import-realm
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      KC_HOSTNAME_PATH: ${KC_HOSTNAME_PATH}
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/tsoftware-realm.json
      KC_HTTPS_KEY_STORE_FILE: /etc/keycloak/server.p12
      KC_HTTPS_KEY_STORE_PASSWORD: ${STORE_PASSWORD}
    restart: always
    volumes:
      - ./tsoftware-realm.json:/opt/keycloak/data/import/tsoftware-realm.json
      - ./server.p12:/etc/keycloak/server.p12
    depends_on:
      - postgres
    networks:
      - qtd_network
  server:
    image: ${SERVER_IMAGE}
    container_name: qtd-server
    environment:
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      OAUTH2_RESOURCESERVER_URI: ${OAUTH2_RESOURCESERVER_URI}
      IDP_URL: ${IDP_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      IDP_REALM: ${IDP_REALM}
    networks:
      - qtd_network
    restart: always
    depends_on:
      - keycloak
      - postgres

  nginx:
    container_name: qtd-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    depends_on:
#      - application
      - server
      - keycloak
    restart: always
    networks:
      - qtd_network
volumes:
  postgres_data:
    driver: local

networks:
  qtd_network:
    name: qtd_network
    driver: bridge
