#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running spotlessApply  "
echo "*********************************************************"


./mvnw spotless:apply

status=$?

if ! [ "$status" -eq 0 ]; then
  echo "*********************************************************"
  echo "       ********************************************      "
  echo "Spotless Apply found violations it could not fix."
  echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
  echo "       ********************************************      "
  echo "*********************************************************"
  exit 1
fi