name: Build app

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for the script
        run: chmod +x decrypt-service-account.sh

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2

#      - name: Generate CodeArtifact Auth Token
#        id: codeartifact-auth-token
#        run: |
#          TOKEN=$(aws codeartifact get-authorization-token \
#            --domain rido \
#            --domain-owner 546505995906 \
#            --region us-west-2 \
#            --query authorizationToken \
#            --output text)
#          echo "TOKEN=$TOKEN"
#          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Decrypt large secret
        run: |
          ./decrypt-service-account.sh 
          ls
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21

#      - name: Add aws to .m2
#        run: |
#          cp ./settings.xml ~/.m2/settings.xml

      # - name: Test
      #   run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B  package -DskipTests --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository to lowercase
        run: echo "LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_REPO }}:latest



